name: Deploy Next.js to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 72.61.233.234
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
                cd /var/www/xyraco/xyraco_project

                echo "Pull latest code"
                git pull origin main

                echo "Install deps"
                npm install

                echo "Clean old build"
                rm -rf .next

                echo "Build project"
                npm run build

                echo "Restart app properly"
                pm2 restart xyraco --update-env